---
language: shell

os:
  - linux

matrix:
  include:
    - dist: focal
    - dist: bionic
    - dist: xenial

sudo: required

cache:
  apt: true
  directories:
    - /usr/local/src

git:
  quiet: true

env:
  global:
    - MAKEFLAGS="-j 2"

before_script:
  - sudo apt-get -qq autoremove --purge

addons:
  apt:
    update: true

script:
  - sudo echo "Travis Banch = $TRAVIS_BRANCH"
  - sudo apt-get install -y wget
  - sudo bash imei.sh --travis || exit 1
