---
name: Main

on:
  push:
    paths:
      - 'imei.sh'
      - 'versions/*.*'
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  ShellCheck:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2.3.4

      - name: Run Shellcheck
        uses: azohra/shell-linter@v0.5.0
        with:
          path: 'imei.sh'

  TestBuild:
    needs: ShellCheck
    runs-on: ubuntu-latest
    
    steps:
      - name: Git checkout
        uses: actions/checkout@v2.3.4

      - name: Build
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |-
          sudo bash imei.sh --ci --log-file "/build.log"
          [[ "$(magick -version)" == *"heic"* ]] && [[ "$(magick -version)" == *"jxl"* ]] && echo "Test build OK" || exit 1

      - name: On failure
        if: ${{ failure() }}
        run: sudo tail -25 /build.log

  Sign:
    needs: TestBuild
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2.3.4

      - name: Sign release
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |-
          echo "$PRIVATE_KEY" > private.pem
          openssl dgst -sha512 -sign private.pem -out imei.sh.sig imei.sh
          rm private.pem

      - name: Verify release
        run: |-
          openssl dgst -sha512 -verify imei.sh.pem -signature imei.sh.sig imei.sh

      - name: Commit and push on changes
        run: |-
          git add .
          git diff
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -m "Updated signature" -a || echo "No changes to commit"
          git push
