---
name: Test

on:
  pull_request:
    paths:
      - 'imei.sh'
      - 'versions/*.*'
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  ShellCheck:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2.3.4

      - name: Run Shellcheck
        uses: azohra/shell-linter@v0.5.0
        with:
          path: 'imei.sh'

  TestBuild:
    needs: ShellCheck
    runs-on: ubuntu-latest
    
    steps:
      - name: Git checkout
        uses: actions/checkout@v2.3.4

      - name: Uninstall ImageMagick
        run: sudo apt-get remove imagemagick* --purge -y

      - name: Build
        run: |
          sudo bash imei.sh --ci --no-sig-verify --log-file "/build.log"
          [[ "$(magick -version)" == *"heic"* ]] && [[ "$(magick -version)" == *"jxl"* ]] && echo "Test build OK" || exit 1

      - name: On failure
        if: ${{ failure() }}
        run: sudo tail -25 /build.log
