name: Update Version Information

on:
  push:
    paths:
      - 'update_version_info.sh'
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  Update:
    runs-on: ubuntu-22.04

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Update Version Information
        run: sudo bash update_version_info.sh -- && echo "OK"

      - name: Commit and push on changes
        run: |-
          git add .
          git diff
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -m "Updated version information" -a || echo "No changes to commit"
          git push
