---
name: UpdateVersionInfo

on:
  push:
    paths:
      - 'update_version_info.sh'
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  Update:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2.3.4

      - name: Update Version Information
        run: sudo bash update_version_info.sh -- && echo "OK"

      - name: Commit and push on changes
        run: |-
          git add .
          git diff
          git config --global user.email "33604303+magickwizard@users.noreply.github.com"
          git config --global user.name "magickwizard"
          git commit -m "Updated version information" -a || echo "No changes to commit"
          git push
